# Generated by Django 3.1.2 on 2022-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0005_auto_20220425_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='map_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
